/*
 * hdpc_com_main.hpp
 *
 *  Created on: Apr 15, 2012
 *      Author: gech
 */

#ifndef HDPC_COM_MAIN_HPP_
#define HDPC_COM_MAIN_HPP_


/* Set CAN bitrate to 1Mbps */
#define BTR0 0x00
#define BTR1 0x14
/* Set CAN bitrate to 500kbps */
//#define BTR0 0x00
//#define BTR1 0x1c


//! struct of bus routine initial arguments
struct BusRoutineArguments {
	// identifier of the bus [0,3]
	int iBus;
	// handle of CAN bus
	int handle;
	// time step in ms
	double time_step_ms;
};


//! RxPDO index of RxPDOManager in busManager
enum RxPDOs {
	RxPDO_SYNC = 0,
	RxPDO_ELMO0,
	RxPDO_ELMO1,
	RxPDO_ELMO2,
	RxPDO_ELMO3,
	RxPDO_ELMO4,
	RxPDO_ELMO5,
	RxPDO_ELMO6,
	RxPDO_ELMO7,
	RxPDO_ELMO8,
	RxPDO_ELMO9,
};

//! TxPDO index of TxPDOManager in busManager
enum TxPDOs {
	TxPDO_ELMO0_POSITION_VELOCITY,
	TxPDO_ELMO0_ANALOG_CURRENT,
	TxPDO_ELMO1_POSITION_VELOCITY,
	TxPDO_ELMO1_ANALOG_CURRENT,
	TxPDO_ELMO2_POSITION_VELOCITY,
	TxPDO_ELMO2_ANALOG_CURRENT,
	TxPDO_ELMO3_POSITION_VELOCITY,
	TxPDO_ELMO3_ANALOG_CURRENT,
	TxPDO_ELMO4_POSITION_VELOCITY,
	TxPDO_ELMO4_ANALOG_CURRENT,
	TxPDO_ELMO5_POSITION_VELOCITY,
	TxPDO_ELMO5_ANALOG_CURRENT,
	TxPDO_ELMO6_POSITION_VELOCITY,
	TxPDO_ELMO6_ANALOG_CURRENT,
	TxPDO_ELMO7_POSITION_VELOCITY,
	TxPDO_ELMO7_ANALOG_CURRENT,
	TxPDO_ELMO8_POSITION_VELOCITY,
	TxPDO_ELMO8_ANALOG_CURRENT,
	TxPDO_ELMO9_POSITION_VELOCITY,
	TxPDO_ELMO9_ANALOG_CURRENT
};

//! shared memory ID of sent messages
enum DESSMID {
	DESSMID_RxPDO_ELMO0_PROFILE = 0,
	DESSMID_RxPDO_ELMO1_PROFILE,
	DESSMID_RxPDO_ELMO2_PROFILE,
	DESSMID_RxPDO_ELMO3_PROFILE,
	DESSMID_RxPDO_ELMO4_PROFILE,
	DESSMID_RxPDO_ELMO5_PROFILE,
	DESSMID_RxPDO_ELMO6_PROFILE,
	DESSMID_RxPDO_ELMO7_PROFILE,
	DESSMID_RxPDO_ELMO8_PROFILE,
	DESSMID_RxPDO_ELMO9_PROFILE,
	DESSMID_RxPDO_SYNC,
	DESSMID_SDO_ELMO0,
	DESSMID_SDO_ELMO1,
	DESSMID_SDO_ELMO2,
	DESSMID_SDO_ELMO3,
	DESSMID_SDO_ELMO4,
	DESSMID_SDO_ELMO5,
	DESSMID_SDO_ELMO6,
	DESSMID_SDO_ELMO7,
	DESSMID_SDO_ELMO8,
	DESSMID_SDO_ELMO9
};

//! shared memory ID of received messages
enum MEASSMID {
	MEASSMID_TxPDO_ELMO0_POSITION_VELOCITY = 0,
	MEASSMID_TxPDO_ELMO1_POSITION_VELOCITY,
	MEASSMID_TxPDO_ELMO2_POSITION_VELOCITY,
	MEASSMID_TxPDO_ELMO3_POSITION_VELOCITY,
	MEASSMID_TxPDO_ELMO4_POSITION_VELOCITY,
	MEASSMID_TxPDO_ELMO5_POSITION_VELOCITY,
	MEASSMID_TxPDO_ELMO6_POSITION_VELOCITY,
	MEASSMID_TxPDO_ELMO7_POSITION_VELOCITY,
	MEASSMID_TxPDO_ELMO8_POSITION_VELOCITY,
	MEASSMID_TxPDO_ELMO9_POSITION_VELOCITY,
	MEASSMID_TxPDO_ELMO0_ANALOG_CURRENT,
	MEASSMID_TxPDO_ELMO1_ANALOG_CURRENT,
	MEASSMID_TxPDO_ELMO2_ANALOG_CURRENT,
	MEASSMID_TxPDO_ELMO3_ANALOG_CURRENT,
	MEASSMID_TxPDO_ELMO4_ANALOG_CURRENT,
	MEASSMID_TxPDO_ELMO5_ANALOG_CURRENT,
	MEASSMID_TxPDO_ELMO6_ANALOG_CURRENT,
	MEASSMID_TxPDO_ELMO7_ANALOG_CURRENT,
	MEASSMID_TxPDO_ELMO8_ANALOG_CURRENT,
	MEASSMID_TxPDO_ELMO9_ANALOG_CURRENT,
	MEASSMID_SDO_ELMO0,
	MEASSMID_SDO_ELMO1,
	MEASSMID_SDO_ELMO2,
	MEASSMID_SDO_ELMO3,
	MEASSMID_SDO_ELMO4,
	MEASSMID_SDO_ELMO5,
	MEASSMID_SDO_ELMO6,
	MEASSMID_SDO_ELMO7,
	MEASSMID_SDO_ELMO8,
	MEASSMID_SDO_ELMO9
};

//! CAN Node ID given by the DIP switches
enum CANNODEID {
	NODEID_ELMO0=1,
	NODEID_ELMO1,
	NODEID_ELMO2,
	NODEID_ELMO3,
	NODEID_ELMO4,
	NODEID_ELMO5,
	NODEID_ELMO6,
	NODEID_ELMO7,
	NODEID_ELMO8,
	NODEID_ELMO9
};


#endif /* HDPC_COM_MAIN_HPP_ */
