#warning: values are probably wrong
uint8 DRIVE_FRONT_LEFT = 0
uint8 DRIVE_FRONT_RIGHT = 1
uint8 DRIVE_MIDDLE_LEFT = 2
uint8 DRIVE_MIDDLE_RIGHT = 3
uint8 DRIVE_REAR_LEFT = 4
uint8 DRIVE_REAR_RIGHT = 5
uint8 STEERING_FRONT_LEFT = 6
uint8 STEERING_FRONT_RIGHT = 7
uint8 STEERING_REAR_LEFT = 8
uint8 STEERING_REAR_RIGHT = 9





# See constant in service SetControlMode.srv
uint8 control_mode
hdpc_com/Readings motors


